

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainBackgroundPanel;
                ref class Grid;
                ref class Button;
                ref class AppBar;
            }
        }
    }
}

namespace Bounce
{
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::SwapChainBackgroundPanel^ SwapChainPanel;
        private: ::Windows::UI::Xaml::Controls::Grid^ MainSelectionGrid;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnPlayFriendsVeryEasy;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnPlayFriendsEasy;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnPlayFriendsNormal;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnPlayFriendsHard;
        private: ::Windows::UI::Xaml::Controls::AppBar^ AppBarBottom;
        private: ::Windows::UI::Xaml::Controls::Button^ BtnDonate;
    };
}

